// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/admin/contractors": {
    params: {};
  };
  "/admin/contractors/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/make-first-admin": {
    params: {};
  };
  "/contractor/profile": {
    params: {};
  };
  "/contractor/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account/logout" | "/account/signin" | "/account/signup" | "/admin/contractors" | "/admin/contractors/:id" | "/admin/dashboard" | "/admin/make-first-admin" | "/contractor/profile" | "/contractor/register" | "/dashboard" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./admin/contractors/page.jsx": {
    id: "admin/contractors/page";
    page: "/admin/contractors";
  };
  "./admin/contractors/[id]/page.jsx": {
    id: "admin/contractors/[id]/page";
    page: "/admin/contractors/:id";
  };
  "./admin/dashboard/page.jsx": {
    id: "admin/dashboard/page";
    page: "/admin/dashboard";
  };
  "./admin/make-first-admin/page.jsx": {
    id: "admin/make-first-admin/page";
    page: "/admin/make-first-admin";
  };
  "./contractor/profile/page.jsx": {
    id: "contractor/profile/page";
    page: "/contractor/profile";
  };
  "./contractor/register/page.jsx": {
    id: "contractor/register/page";
    page: "/contractor/register";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "account/signup/page": typeof import("./src/app/./account/signup/page.jsx");
  "admin/contractors/page": typeof import("./src/app/./admin/contractors/page.jsx");
  "admin/contractors/[id]/page": typeof import("./src/app/./admin/contractors/[id]/page.jsx");
  "admin/dashboard/page": typeof import("./src/app/./admin/dashboard/page.jsx");
  "admin/make-first-admin/page": typeof import("./src/app/./admin/make-first-admin/page.jsx");
  "contractor/profile/page": typeof import("./src/app/./contractor/profile/page.jsx");
  "contractor/register/page": typeof import("./src/app/./contractor/register/page.jsx");
  "dashboard/page": typeof import("./src/app/./dashboard/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};